### ISSUE TITLE
Mavenize docker image build

### ISSUE THREAD

**Issue by mohamed-taman** [mohamed-taman/Springy-Store-Microservices#16]
As an Architect, I want to enhance the microservices dockerization by using a maven plugin, so that the docker image will be created automatically during the build process.

**Requirements**
- use **dockerfile-maven-plugin** for more control with docker file [Plugin Link](https://github.com/spotify/dockerfile-maven).

- Add ***IMAGE_VERSION*** and ***IMAGE_NAME*** arguments to be passed dynamically from the pom.xml file.

**Comment by mohamed-taman** [comment]
Hi @nickstolwijk 
Thanks very much for your suggestion.

Can I ask you to open an issue for that explaining how it should work for our project:
1. What to add in our project as dependencies, 
2. What will be inside the `modernizer.marker`,
3. And the command line to run it.

So if it makes sense, I will assign it to you to collaborate and submit a pull request for such enhancement?

So what do you think?

**Comment by nickstolwijk** [comment]
I will try to make a PR to show what I mean.

**Comment by nickstolwijk** [comment]
This example was for another plugin, the modernizer plugin. The marker is just an empty file to indicate that the plugin (which is configured in the parent) should be activated.

**Comment by nickstolwijk** [comment]
My build is failing on log4j:log4j:jar:1.2.17-atlassian-1.

- Where did you get this artifact?
- Why do you still use log4j instead of SLF4j, Log4j 2 or Logback?
