### ISSUE TITLE
Introducing Spring Open Feign

### ISSUE THREAD

**Issue by sweelam** [mohamed-taman/Springy-Store-Microservices#3]
**Is code a good place for URLs?**
This is the catch, urls are always a problem, and add to that location for each service ; so better to use Open Feign project.

**Comment by mohamed-taman** [comment]
Thanks, Sweelam, 

First thanks very much for the issue.

I am developing this project in stages, for example, first building the services skeletons, and all communication is static as you have seen with random contents, second stage adding database, third introduce service discovery to get rid of static URL communication and using service name, then dockerize the application, and so on.

I will update the readme file to reflect these clarifications.
