### ISSUE TITLE
Updating the automated tests of the Microservices landscape with new functionalities.

### ISSUE THREAD

**Issue by mohamed-taman** [mohamed-taman/Springy-Store-Microservices#39]

**Comment by wilferraciolli** [comment]
Hi

Do you plan to add security? I am studying a similar project. called microservices template (AuthServer, Zulll, Eureka, Resource, RabbitMQ, Angular,Docker...) and though it this is very similar.
Also piggy metrics is a good source.
I am having issues with performance as at the moment, the Zull gateway and each microservice makes a trip to the auth server to validate the token

**Comment by mohamed-taman** [comment]
I am working on stages (aka. Releases), and in the near future, I will add all of those cloud-native components you have mentioned above, in the next stages especially Auth service, and edge server so I will make them early stages and you can collaborate in this project if you would like, by opening issues or PRs.
