### ISSUE TITLE
Eureka Discovery Server Build Failed

### ISSUE THREAD

**Issue by benstitou** [mohamed-taman/Springy-Store-Microservices#66]
When running `./mvnw clean verify -Ddockerfile.skip` the build fail on building "Eureka Discovery Server" due to `${app.eureka.user}` not found

![image](https://user-images.githubusercontent.com/28157516/82580979-66702980-9b7f-11ea-9f86-5625c3821514.png)

**Desktop:**
 - OS: Windows 10
 - Java 14
 - Maven 3.6.1

**Possible Solution**
Add `app.eureka.user` and `app.eureka.pass` values to `bootstrap.yml`

**Comment by mohamed-taman** [comment]
@benstitou Thanks very much, I was able to reproduce it, will fix it and update repository as soon as possible.
