### ISSUE TITLE
unable to start Springy Store

### ISSUE THREAD

**Issue by nvkforl** [mohamed-taman/Springy-Store-Microservices#86]
![image](https://user-images.githubusercontent.com/55645610/103139344-34b8d580-4701-11eb-8ea4-c9e4cb4761b9.png)
![image](https://user-images.githubusercontent.com/55645610/103139361-69c52800-4701-11eb-8781-d5864a555f7d.png)

**Comment by nvkforl** [comment]
Thanks for this wonderful project, can you please resolve this issue as no data is been fetched from the store api

**Comment by mohamed-taman** [comment]
@nvkforl Sorry for the late response, but it works fine from the pictures, and all test cases pass successfully.
I intentionally testing the APIs when there is no data to be fetched from API, so check about error messages.
